# Generated by Django 4.0.3 on 2022-03-18 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0001_initial'),
        ('supers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='super',
            name='primary_ability',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='primary_ability', to='powers.power'),
        ),
        migrations.AlterField(
            model_name='super',
            name='secondary_ability',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='secondary_ability', to='powers.power'),
        ),
    ]
