# Generated by Django 4.0.3 on 2022-03-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0002_alter_super_primary_ability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='super',
            name='primary_ability',
        ),
        migrations.RemoveField(
            model_name='super',
            name='secondary_ability',
        ),
    ]
