# Generated by Django 4.0.3 on 2022-03-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0003_remove_super_primary_ability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='super',
            name='primary_ability',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='super',
            name='secondary_ability',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
