# Generated by Django 4.0.3 on 2022-03-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powers', '0001_initial'),
        ('supers', '0006_super_primary_ability_super_secondary_ability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='super',
            name='primary_ability',
        ),
        migrations.AddField(
            model_name='super',
            name='primary_ability',
            field=models.ManyToManyField(related_name='Primary_Power', to='powers.power'),
        ),
        migrations.RemoveField(
            model_name='super',
            name='secondary_ability',
        ),
        migrations.AddField(
            model_name='super',
            name='secondary_ability',
            field=models.ManyToManyField(related_name='Secondary_Power+', to='powers.power'),
        ),
    ]
