# Generated by Django 4.0.3 on 2022-03-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0007_remove_super_primary_ability_super_primary_ability_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super',
            old_name='primary_ability',
            new_name='powers',
        ),
        migrations.RemoveField(
            model_name='super',
            name='secondary_ability',
        ),
    ]
